import { publicUrl } from '../../lib/publicAsset'

type Props = {
  /** Path under site root, usually `/screenshots/*.png` */
  src: string
  alt: string
  width: number
  height: number
  className?: string
  loading?: 'eager' | 'lazy'
  decoding?: 'async' | 'auto' | 'sync'
  fetchPriority?: 'high' | 'low' | 'auto'
  onError?: () => void
}

/** PNG fallback with WebP `<source>` when a sibling `.webp` exists (generated by `npm run optimize-screenshots`). */
export function ScreenshotImg({
  src,
  alt,
  width,
  height,
  className,
  loading = 'lazy',
  decoding = 'async',
  fetchPriority,
  onError,
}: Props) {
  const pngSrc = publicUrl(src)
  const webpSrc = src.toLowerCase().endsWith('.png') ? publicUrl(`${src.slice(0, -4)}.webp`) : undefined

  return (
    <picture>
      {webpSrc ? <source type="image/webp" srcSet={webpSrc} /> : null}
      <img
        src={pngSrc}
        alt={alt}
        width={width}
        height={height}
        className={className}
        loading={loading}
        decoding={decoding}
        fetchPriority={fetchPriority}
        onError={onError}
      />
    </picture>
  )
}
